services:
  proxy:
    image: caddy

    environment:
      SSL_CERTIFICATE_PATH: /etc/certs/cert.pem
      SSL_KEY_PATH: /etc/certs/key.pem

    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"

    volumes:
      - ../caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

    secrets:
      - source: ssl-certificate
        target: /etc/certs/cert.pem
      - source: ssl-key
        target: /etc/certs/key.pem

    networks:
      - caddy

volumes:
  caddy_data:
    external: true
  caddy_config:

networks:
  caddy:
    external: true

secrets:
  ssl-certificate:
    external: true
  ssl-key:
    external: true
