version: "3"
services:
  database:
    image: postgres:14.2
    volumes:
      - database:/var/lib/postgresql/data
      - ${RALLLY_DATABASE_INIT}:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: ${RALLLY_DATABASE_PASSWORD}
      POSTGRES_DB: db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 5005:5432

  rallly:
    image: lukevella/rallly:3
    depends_on:
      database:
        condition: service_healthy
    environment:
      SECRET_PASSWORD: ${RALLLY_SECRET_PASSWORD}

      DATABASE_URL: postgres://rallly:${RALLLY_DATABASE_PASSWORD}@database:5432/rallly
      # REQUIRED CONFIG
      # The base url where this instance is accessible, including the scheme.
      # Example: https://example.com
      NEXT_PUBLIC_BASE_URL: https://clic.epfl.ch/rallly

      # EMAIL CONFIG (required for sending emails)

      # All outgoing emails will show this email as the sender's email address, which also serves as the support email.
      SUPPORT_EMAIL: it.clic@epfl.ch
      # The host address of your SMTP server
      SMTP_HOST: mail.epfl.ch
      # The username (if auth is enabled on your SMTP server)
      SMTP_USER: it.clic
      # The password (if auth is enabled on your SMTP server)
      SMTP_PWD: ${SMTP_IT_PASSWORD}
      # The port of your SMTP server
      SMTP_PORT: 587
      # Set to "true" if SSL is enabled for your SMTP connection
      SMTP_SECURE: "true"
      # Set to "true" to enable TLS. Might be needed for some SMTP connections
      SMTP_TLS_ENABLED: "false"
      
    networks:
      default:
      caddy:

networks:
  caddy:
    external: true

volumes:
  database: