services:
  vaultwarden:
    image: vaultwarden/server:1.29.2-alpine
    hostname: vaultwarden
    volumes:
      - vaultwarden:/data
    env_file: .env
    environment:
      DOMAIN: https://clic.epfl.ch/armoire
    
    networks:
      caddy:

networks:
  caddy:
    external: true
volumes:
  vaultwarden: