services:
  vaultwarden:
    hostname: vaultwarden
    image: vaultwarden/server
    volumes:
      - vaultwarden:/data
    env_file: .env
    environment:
      DOMAIN: https://clic.epfl.ch/armoire
    
    networks:
      caddy:

networks:
  caddy:
    external: true
volumes:
  vaultwarden: