services:
  bookstack:
    image: lscr.io/linuxserver/bookstack
    hostname: bookstack
    environment:
      PUID: 1000
      PGID: 1000
      APP_URL: https://clic.epfl.ch/bookstack
      DB_HOST: database
      DB_PORT: 3306
      DB_USER: bookstack
      DB_PASS: ${BOOKSTACK_DATABASE_PASSWORD}
      DB_DATABASE: bookstackapp
      MAIL_DRIVER: smtp
      MAIL_HOST: mail.epfl.ch
      MAIL_PORT: 587
      MAIL_ENCRYPTION: starttls
      MAIL_USERNAME: it.clic
      MAIL_PASSWORD: ${SMTP_IT_PASSWORD}
      MAIL_FROM: it.clic@epfl.ch
      MAIL_FROM_NAME: CLIC - Bookstack
    volumes:
      - app:/config
    networks:
      default:
      caddy:
    depends_on:
      - database

  database:
    image: lscr.io/linuxserver/mariadb
    hostname: database
    environment:
      PUID: 1000
      PGID: 1000
      MYSQL_ROOT_PASSWORD: ${BOOKSTACK_DATABASE_PASSWORD}
      TZ: Europe/London
      MYSQL_DATABASE: bookstackapp
      MYSQL_USER: bookstack
      MYSQL_PASSWORD: ${BOOKSTACK_DATABASE_PASSWORD}
    volumes:
      - database:/config
      - ${BOOKSTACK_DATABASE_INIT}:/docker-entrypoint-initdb.d
    ports:
      - 5004:3306

volumes:
  database:
  app:
networks:
  caddy:
    external: true
