services:
  mediawiki:
    image: mediawiki:1.40.0
    hostname: wiki
    working_dir: /var/www/html/mediawiki
    env_file:
      - ../wiki/.env
    volumes:
      - images:/var/www/html/mediawiki/images
      - ../wiki/LocalSettings.php:/var/www/html/LocalSettings.php
    depends_on:
      - database
    networks:
      default:
      caddy:

  database:
    image: mariadb:10.5
    env_file:
      - ../wiki/database.env
    environment:
      MYSQL_DATABASE: my_wiki
      MYSQL_USER: wikiuser
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - database:/var/lib/mysql

volumes:
  images:
  database:
networks:
  caddy:
    external: true
