version: '3.6'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://database:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}

      KC_HOSTNAME_URL: https://clic.epfl.ch/keyclic
      KC_HOSTNAME_STRICT: "false"

      KC_HTTP_ENABLED: "true"
      KC_HTTP_RELATIVE_PATH: /keyclic
      KC_HTTPS_PORT: 443
      KC_PROXY: edge

      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: "true"
      KC_HEALTH_ENABLED: "true"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    volumes:
      - ./clic_theme:/opt/keycloak/themes/clic_theme
    command: start
    depends_on:
      - database
    ports:
      - 8008:8080

  database:
    image: postgres:15
    hostname: database
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    ports:
      - 5006:5432

volumes:
  data:
  clic_theme: