services:
  database:
    image: mariadb:10.5
    volumes:
      - nextcloud-db:/var/lib/mysql
    env_file: database.env
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud

  nextcloud:
    image: nextcloud:27-apache
    hostname: nextcloud
    volumes:
      - nextcloud-app:/var/www/html
    env_file: app.env
    environment:
      NC_overwriteprotocol: https
      NC_overwritehost: clic.epfl.ch
      NC_overwritewebroot: /nextcloud

      NC_dbtype: mysql
      NC_dbhost: database
      NC_dbname: nextcloud
      NC_dbuser: nextcloud
    networks:
      caddy:
      default:

  cron:
    image: nextcloud:27-apache
    volumes:
      - nextcloud-app:/var/www/html
    env_file: app.env
    environment:
      NC_overwriteprotocol: https
      NC_overwritehost: clic.epfl.ch
      NC_overwritewebroot: /nextcloud

      NC_dbtype: mysql
      NC_dbhost: database
      NC_dbname: nextcloud
      NC_dbuser: nextcloud
    entrypoint: /cron.sh

networks:
  caddy:
    external: true

volumes:
  nextcloud-db:
  nextcloud-app:
