services:
  database:
    image: mariadb:10.5
    volumes:
      - nextcloud-db:/var/lib/mysql
    env_file: database.env
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud

  nextcloud:
    image: nextcloud:27-apache
    volumes:
      - nextcloud-app:/var/www/html        
    env_file: 
      - app.env
      - config.env
    networks:
      caddy:
      default:

  cron:
    image: nextcloud:27-apache
    volumes:
      - nextcloud-app:/var/www/html
    env_file: 
      - app.env
      - config.env
    entrypoint: /cron.sh

networks:
  caddy:
    external: true

volumes:
  nextcloud-db:
  nextcloud-app:
