services:
  collabora:
    image: collabora/code:latest
    hostname: collabora
    configs:
      - source: config
        target: /etc/coolwsd/coolwsd.xml
    environment:
      username: admin
      password: ${COLLABORA_ADMIN_PASSWORD}
      extra_params: --o:ssl.enable=false --o:ssl.termination=true
      DONT_GEN_SSL_CERT: 1
      server_name: https://clic.epfl.ch:9980
    networks:
      - caddy

configs:
  config:
    file: ./coolwsd.xml
networks:
  caddy:
    external: true
