- name: Deploy all services
  hosts: all
  tasks:
    - name: Deploy
      loop: "{{ [wiki, vaultwarden, roboclic] }}"
      community.docker.docker_stack:
        state: present
        name: "{{ item }}"
        resolve_image: changed
        compose:
          - "../{{ item }}/docker-compose.yaml"
