- name: Initialize server
  hosts: all
  tasks:
    - name: Update APT packages
      ansible.builtin.apt:
        update_cache: true
        upgrade: true

    - name: Install required packages
      ansible.builtin.apt:
        pkg:
          - docker
          - cron

    - name: Init Docker swarm
      community.docker.docker_swarm:
        state: present

    - name: Mount secondary disk onto backup directory
      ansible.posix.mount:
        state: mounted
        path: "{{ ansible_env.BACKUP_DIR }}"
        src: "{{ ansible_env.BACKUP_DISK }}"
        fstype: ext4

    - name: Init backup repository
      ansible.builtin.command:
        argv:
          - borg
          - init
          - -e
          - none
          - "{{ ansible_env.BACKUP_DIR }}"
      register: out
      changed_when: out.rc == 0

    - name: Launch borgmatic
      ansible.builtin.include_role:
        name: borgbase.ansible_role_borgbackup

  roles:
    - role: borgbase.ansible_role_borgbackup
      borg_repository: "{{ ansible_env.BACKUP_DIR }}"
      borgmatic_timer: cron
      borgmatic_timer_hour: 0
      borgmatic_timer_minute: 0
      borg_source_directories:
      borgmatic_hooks:
        before_backup:
          - echo "`date` - Starting backup."
        postgresql_databases:
      borg_retention_policy:
        keep_hourly: 3
        keep_daily: 7
        keep_weekly: 4
        keep_monthly: 6
